

# HTTP 重定向到 HTTPS
server {
    server_name pindou.znclub.vip;
   
    root /var/www/pindou;
    index index.html;
    # 处理 Next.js 静态导出的 SPA 路由
    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }   

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/pindou.znclub.vip/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pindou.znclub.vip/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = pindou.znclub.vip) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name pindou.znclub.vip;
    return 404; # managed by Certbot


}